AllCops:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - '**/Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
