AllCops:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - '**/Gemfile'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
  Max: 15

Rails/Output:
  Exclude:
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
