AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - '**/Gemfile'
    - 'config/environments/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
